[[redirects]]
  from = "/api/*"
  to = "https://ateam-server.tk/:splat"
  status = 302

[[redirects]]
  from = "/api"
  to = "https://ateam-server.tk"
  status = 302

[[redirects]]
  from = "/"
  to ="/index.html"
  status = 200 